#!/bin/bash

# This script tranforms all *.xml files in the examples folder into OpenAPI 2.0 and OpenAPI 3.0 JSON files
#
# Prerequisites
# - Java           sudo apt-get install default-jre
# - Git            sudo apt-get install git
# - Xalan 2.7.1    sudo apt-get install libxalan2-java
# - json_reformat  sudo apt-get install yajl-tools
# - Node.js        sudo apt-get install nodejs
#                  sudo apt-get install nodejs-legacy
# - npm            sudo apt-get install npm
# - ajv-cli        sudo npm install -g ajv-cli
# - https://github.com/OAI/OpenAPI-Specification is cloned next to this project
SCHEMA_THREE=openapi-3.0.0.schema.json
SCHEMA_TWO=../../OpenAPI-Specification/schemas/v2.0/schema.json

process() {
  local name=${1##*/}; name=${name%.*}
  echo $name
  
  if [ "$5" = "V2" ]
  then
    java -cp /usr/share/java/xalan2.jar org.apache.xalan.xslt.Process -L -XSL V2-to-V4-CSDL.xsl -IN ../examples/$1 -OUT $name.V4.xml
    VERSION="2.0"
    INPUT="$name.V4.xml"
  elif [ "$5" = "V3" ]
  then
    java -cp /usr/share/java/xalan2.jar org.apache.xalan.xslt.Process -L -XSL V2-to-V4-CSDL.xsl -IN ../examples/$1 -OUT $name.V4.xml
    VERSION="3.0"
    INPUT="$name.V4.xml"
  else
    VERSION="4.0"
    INPUT="../examples/$1"
  fi
  
  java -cp /usr/share/java/xalan2.jar org.apache.xalan.xslt.Process -L -XSL V4-CSDL-to-OpenAPI.xsl -PARAM scheme $2 -PARAM host $3 -PARAM basePath $4 -PARAM odata-version $VERSION -PARAM diagram YES -PARAM references YES -PARAM openapi-root "https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/" -PARAM openapi-version 3.0.0 -IN $INPUT -OUT $name.tmp3.json
  
  json_reformat < $name.tmp3.json > ../examples/$name.openapi3.json
  if [ $? = 0 ]
  then 
    rm $name.tmp3.json
    git --no-pager diff --ignore-space-at-eol ../examples/$name.openapi3.json  
    
    [ -f $SCHEMA_THREE ] && ajv validate --unknown-formats=uriref -s $SCHEMA_THREE -d ../examples/$name.openapi3.json > /dev/null
  fi

  java -cp /usr/share/java/xalan2.jar org.apache.xalan.xslt.Process -L -XSL V4-CSDL-to-OpenAPI.xsl -PARAM scheme $2 -PARAM host $3 -PARAM basePath $4 -PARAM odata-version $VERSION -PARAM diagram YES -PARAM references YES -PARAM openapi-root "https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/" -IN $INPUT -OUT $name.tmp.json
  
  json_reformat < $name.tmp.json > ../examples/$name.openapi.json
  if [ $? = 0 ]
  then 
    rm $name.tmp.json
    if [ "$5" = "V2" ] || [ "$5" = "V3" ]; then rm $name.V4.xml; fi
    git --no-pager diff --ignore-space-at-eol ../examples/$name.openapi.json  
    [ -f $SCHEMA_TWO ] && ajv validate -s $SCHEMA_TWO -d ../examples/$name.openapi.json > /dev/null
  fi
}

while IFS=$' \r' read f g h i j || [[ -n "$f" ]]
do
  if [ -n "$f" ] && [ "${f:0:1}" != "#" ]
  then
    if [ -z "$1" ] || [ "$f" = "$1" ] || [ "$f" = "$1.xml" ]
    then
      DONE="yes"
      process $f $g $h $i $j
    fi
  fi
done < $0.txt

if [ -z "$DONE" ]
then
  for file in $*
  do
    if [ -f $file  ]
    then
      process $file http localhost /service-root 
    else
      echo File not found: $file
    fi
  done
fi
